name: JS lints

on:
  push:

jobs:
  frontend-lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json

      - name: Install ESLint deps
        run: npm install eslint @eslint/js eslint-plugin-unicorn eslint-plugin-sonarjs eslint-plugin-import-x vite svelte @sveltejs/vite-plugin-svelte

      - name: Run ESLint
        run: npx eslint .
